export const START_MATCH = 'START_MATCH';
export const MOVE_SELECTED = 'MOVE_SELECTED';
export const END_MATCH = 'END_MATCH';
export const END_ROUND = 'END_ROUND';
export const RESTART_GAME = 'RESTART_GAME'

export const SHOW_STATISTICS = 'SHOW_STATISTICS';
export const HIDE_STATISTICS = 'HIDE_STATISTICS';